### ISSUE TITLE
Grokker - customPatternDir default value "" causes error

### ISSUE THREAD

**Issue by niklas-kunz** [fkie-cad/Logprep#490] opened 2023-12-06 14:12 UTC
## Description: 

In FDA, we use the following logic to determine if a rule/processor configuration parameter is optional:

```
If the config parameter has a default value:
- config parameter is considered optional
- default value is set in the frontend by default and used if not actively overwritten by the user
```

For an example of how this works, refer to the Pseudonymizer field "targetField" which is optional and has an empty string as default.

This behaviour, however, does not work for the parameter "customPatternsDir", which also has an empty string as default value.

### Example Grokker Configuration
![image](https://github.com/fkie-cad/Logprep/assets/126550886/ceb96de6-7707-44a4-b3fe-65c65910a297)

![image](https://github.com/fkie-cad/Logprep/assets/126550886/c09b24fb-ec55-4ca9-a52e-071453257cec)

### Generated config sent to Logprep
Note how "custom_patterns_dir" is set to "".
```
{
  "position": 6,
  "document": {...},
  "processorType": "grokker",
  "genericRules": [
    {
      "filter": "@timestamp",
      "description": "",
      "grokker": {
        "regex_fields": [],
        "tests": [],
        "tag_on_failure": [],
        "delete_source_fields": false,
        "overwrite_target": false,
        "extend_target_list": false,
        "convert_datatype": {},
        "patterns": {},
        "mapping": {
          "@timestamp": [
            "%{DATE:info.date}T10:12:31.296Z"
          ]
        }
      }
    }
  ],
  "specificRules": [],
  "apply_multiple_times": false,
  "custom_patterns_dir": ""
}
```

### Error returned from Logprep
```
{
    "data": {},
    "errors": [
        {
            "type": "ValidationError",
            "code": "blank",
            "description": "This field may not be blank.",
            "helpText": null,
            "path": "customPatternsDir",
            "fieldDescription": "customPatternsDir"
        }
    ]
}
```

## Expected Behavior
We would expect Logprep to accept the default empty string, meaning that no custom pattern directory is defined.

**Comment by niklas-kunz** [comment] 2023-12-06 14:13
FYI @PMC-BA

**Comment by dtrai2** [comment] 2023-12-14 08:02
Hi @niklas-kunz I sadly cannot reproduce this issue. I started logprep with the quickstart setup and added the grokker into the pipeline. I used the following snippet: 

```yaml
  - grokker:
      type: grokker
      specific_rules:
        - tests/testdata/unit/grokker/specific_rules
      generic_rules:
        - tests/testdata/unit/grokker/generic_rules
      custom_patterns_dir: "tests/testdata/unit/grokker/patterns"
```

and I tried running logprep with the `custom_patterns_dir: "tests/testdata/unit/grokker/patterns"` and with `custom_patterns_dir: ""`. In both cases logprep starts normally and I can see the `Finished building pipeline` output in the logs. 

I also noticed that you reference the "targetField" of the Pseudonymizer. That processor does not have such a field though. I assume that was just a typo and you meant a different processor? 

Can you maybe give me more details on how you start logprep and when this error is returned? Or also which version you used?

**Comment by niklas-kunz** [comment] 2023-12-14 08:51
Thank you for verifying that the default empty string works as expected. I assume that our issue is therefore either related to our Logprep version (6.2.0), which we are currently updating to the newest version. Otherwise, we might call Logprep incorrectly and need to fix that in the FDA backend. In any case, you can close this issue.

Regarding the targetField example – this was indeed from the requester configuration, not from the pseudonymizer.

**Comment by dtrai2** [comment] 2023-12-15 09:10
okay, than I close this. If I should check something else, just let me know. :)

**Closed by dtrai2** 2023-12-15 09:10 UTC
Labels: bug
