### ISSUE TITLE
Config validation does not show processor anymore

### ISSUE THREAD

**Issue by ppcad** [fkie-cad/Logprep#124] opened 2022-06-22 07:43 UTC
The configuration validation does not show the processor name anymore if there is an error in the configuration.

**Expected behavior**
The configuration validation shows the processor name if there is an error in the configuration.

**Current behavior**
The configuration validation shows "__init__()" instead of the processor name if there is an error in the configuration ("Invalid processor config: __init__() ...").

**Steps to reproduce**

1. Create a config that would be valid, but remove something, like "specific_rules"
2. Run logprep
3. See an error like "Invalid processor config: __init__() ..."

**Environment**

Logprep version: 8de3b071d4e137b343a34871cf09e9d95a362b03
Python version: 3.6-3.9

**Comment by dtrai2** [comment] 2022-08-05 12:50
If I try to reproduce this bug in the latest logprep version in the main branch I already get a processor name in the error message. For example:
```
Invalid processor config: labelername - __init__() missing 1 required keyword-only argument: 'specific_rules'
```
includes `labelername` as indicator of the processor.

So @ppcad this bug seems to be fixed already then. Please revise and maybe close this issue if possible.

**Comment by ppcad** [comment] 2022-08-05 12:54
Sorry, I meant the name of the processor type. It should be:
`Invalid processor config: labelername - labeler missing 1 required keyword-only argument: 'specific_rules'`
The __init__() should not be there.
I change the issue accordingly.

**Closed** 2022-08-05 12:58 UTC
Labels: bug
